/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author robby
 */
public class InterfaceGUI4 extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGUI4
     */
    public InterfaceGUI4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output_poli = new javax.swing.JTextArea();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelanimasi = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        server_poli = new javax.swing.JSpinner();
        server_awal = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        output2 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        queue_capacity = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        server_poli2 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        server_poli3 = new javax.swing.JSpinner();
        jLabel38 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        slider = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        play = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        pause = new javax.swing.JToggleButton();
        stop = new javax.swing.JToggleButton();
        report = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        open = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        file_name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        fc.setApproveButtonText("");
        fc.setDialogTitle("Choose File");

        jFrame1.getContentPane().setLayout(null);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel39.setText("jLabel39");
        jFrame1.getContentPane().add(jLabel39);
        jLabel39.setBounds(590, 160, 400, 13);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel40.setText("jLabel40");
        jFrame1.getContentPane().add(jLabel40);
        jLabel40.setBounds(590, 190, 400, 13);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel41.setText("jLabel41");
        jFrame1.getContentPane().add(jLabel41);
        jLabel41.setBounds(590, 220, 400, 13);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel42.setText("jLabel42");
        jFrame1.getContentPane().add(jLabel42);
        jLabel42.setBounds(590, 250, 400, 13);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel43.setText("jLabel43");
        jFrame1.getContentPane().add(jLabel43);
        jLabel43.setBounds(590, 280, 400, 13);

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel44.setText("jLabel44");
        jFrame1.getContentPane().add(jLabel44);
        jLabel44.setBounds(590, 310, 400, 13);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel45.setText("jLabel45");
        jFrame1.getContentPane().add(jLabel45);
        jLabel45.setBounds(590, 340, 400, 13);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel46.setText("jLabel46");
        jFrame1.getContentPane().add(jLabel46);
        jLabel46.setBounds(590, 370, 410, 13);

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel47.setText("jLabel47");
        jFrame1.getContentPane().add(jLabel47);
        jLabel47.setBounds(590, 400, 410, 13);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 47, 570, 350);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel48.setText("Pemodelan dan Simulasi Antrian Pasien di Poliklinik");
        jFrame1.getContentPane().add(jLabel48);
        jLabel48.setBounds(120, 0, 660, 29);

        jLabel49.setText("Output Pelayanan Poliklinik : ");
        jFrame1.getContentPane().add(jLabel49);
        jLabel49.setBounds(650, 40, 149, 17);

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel50.setText("jLabel50");
        jFrame1.getContentPane().add(jLabel50);
        jLabel50.setBounds(10, 403, 120, 13);

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel51.setText("jLabel51");
        jFrame1.getContentPane().add(jLabel51);
        jLabel51.setBounds(155, 403, 100, 13);

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel52.setText("jLabel52");
        jFrame1.getContentPane().add(jLabel52);
        jLabel52.setBounds(294, 403, 150, 13);

        output_poli.setEditable(false);
        output_poli.setColumns(20);
        output_poli.setRows(5);
        jScrollPane1.setViewportView(output_poli);

        jFrame1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(586, 65, 270, 70);
        jFrame1.getContentPane().add(jSeparator14);
        jSeparator14.setBounds(0, 35, 1000, 2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 1152, 768));
        getContentPane().setLayout(null);

        jLabel1.setText("Jumlah Server  Pendaftaran Awal : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 230, 17);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PEMODELAN & SIMULASI ANTRIAN PASIEN  RS TNI AU DR.M.SALAMUN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 0, 750, 23);

        jLabel3.setText("Jumlah Server Poilklinik  :  ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 110, 200, 17);

        panelanimasi.setLayout(null);
        getContentPane().add(panelanimasi);
        panelanimasi.setBounds(6, 176, 670, 430);

        jLabel13.setText("Loket");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 50, 28, 17);

        jLabel14.setText("Dokter");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(300, 110, 35, 17);

        server_poli.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        server_poli.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        getContentPane().add(server_poli);
        server_poli.setBounds(250, 110, 39, 20);

        server_awal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        server_awal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(server_awal);
        server_awal.setBounds(250, 50, 39, 20);

        output2.setEditable(false);
        output2.setColumns(20);
        output2.setRows(5);
        output2.setText("Output Statistik Kedatangan: ");
        jScrollPane2.setViewportView(output2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(730, 180, 279, 70);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(690, 290, 380, 13);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(690, 320, 380, 13);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(690, 350, 380, 13);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(690, 380, 380, 13);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(690, 410, 380, 13);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(690, 440, 380, 13);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(690, 470, 380, 13);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel27.setText("jLabel27");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(690, 500, 380, 13);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel28.setText("jLabel28");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(690, 530, 380, 13);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setText("jLabel30");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(730, 250, 90, 13);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setText("jLabel31");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(820, 250, 100, 13);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel32.setText("jLabel32");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(940, 250, 120, 13);

        jLabel33.setText("Kapasitas Antrian Awal :");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(470, 50, 160, 17);

        jLabel34.setText("pasien");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(680, 50, 33, 17);

        queue_capacity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(queue_capacity);
        queue_capacity.setBounds(630, 50, 39, 20);

        jLabel35.setText("Jumlah Server Poliklinik :");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(52, 80, 190, 17);

        server_poli2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        server_poli2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        getContentPane().add(server_poli2);
        server_poli2.setBounds(250, 80, 40, 20);

        jLabel36.setText("Perawat");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(300, 80, 41, 17);

        jLabel37.setText("Jumlah Server Poliklinik :");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(50, 140, 190, 17);

        server_poli3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        server_poli3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        getContentPane().add(server_poli3);
        server_poli3.setBounds(250, 140, 40, 20);

        jLabel38.setText("Petugas");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(300, 140, 39, 17);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(410, 30, 20, 140);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 170, 280, 20);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(270, 170, 400, 10);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(670, 170, 400, 20);
        getContentPane().add(jSeparator13);
        jSeparator13.setBounds(0, 30, 1070, 10);

        slider.setMaximum(900);
        slider.setMinimum(100);
        slider.setValue(500);
        slider.setEnabled(false);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        getContentPane().add(slider);
        slider.setBounds(10, 620, 390, 23);

        jLabel9.setText("Slower");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 650, 60, 10);

        jLabel8.setText("Real Time");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 650, 80, 17);

        jLabel10.setText("Faster");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 650, 40, 17);

        play.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(440, 620, 60, 21);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("GET TABLE");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 650, 110, 21);

        pause.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        getContentPane().add(pause);
        pause.setBounds(520, 620, 59, 21);

        stop.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop);
        stop.setBounds(600, 620, 60, 21);

        report.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        report.setText("GET REPORT");
        report.setEnabled(false);
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        getContentPane().add(report);
        report.setBounds(560, 650, 100, 21);

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("Back to Main Menu");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(790, 633, 160, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(790, 590, 155, 23);

        jLabel4.setText("Pilih File :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 90, 120, 20);

        open.setText("OPEN FILE");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        getContentPane().add(open);
        open.setBounds(630, 90, 100, 25);

        jLabel5.setText("Nama File : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 140, 80, 17);
        getContentPane().add(file_name);
        file_name.setBounds(630, 134, 290, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(540, 130, 430, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(540, 162, 430, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        int value=slider.getValue();
        int temp=0;
        if(value>500){
            temp=value-500;
            value=500-temp;
        }
        else if(value<500){
            temp=500-value;
            value=500+temp;
        }
        
    }//GEN-LAST:event_sliderStateChanged

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        //Simulation sim;
        

    }//GEN-LAST:event_playActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed

        // TODO add your handling code here:
        play.setEnabled(true);
        pause.setEnabled(false);
        slider.setEnabled(true);
        stop.setEnabled(true);
        jButton1.setEnabled(true);
        report.setEnabled(true);
        back.setEnabled(true);

    }//GEN-LAST:event_pauseActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        play.setEnabled(true);
        slider.setEnabled(false);
        stop.setEnabled(false);
        pause.setEnabled(false);
        jButton2.setEnabled(true);
        back.setEnabled(false);
        

    }//GEN-LAST:event_stopActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_reportActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        InterfaceAwal home=new InterfaceAwal();
        home.pack();
        home.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_backActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.server_awal.setValue(1);
        this.server_poli.setValue(1);
        this.server_poli2.setValue(1);
        this.server_poli3.setValue(1);
        this.queue_capacity.setValue(1);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
    
        jLabel30.setVisible(false);
        jLabel31.setVisible(false);
        jLabel32.setVisible(false);
        slider.setValue(500);
        output2.setText("Output Statistik Kedatangan:");
        this.play.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==open){
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                //This is where a real application would open the file.
                System.out.println(file.getName());
                file_name.setText(file.getName());
               
            } else {
               
            }
        }
    }//GEN-LAST:event_openActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGUI4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGUI4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel file_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton open;
    private javax.swing.JTextArea output2;
    private javax.swing.JTextArea output_poli;
    private javax.swing.JPanel panelanimasi;
    private javax.swing.JToggleButton pause;
    private javax.swing.JToggleButton play;
    private javax.swing.JSpinner queue_capacity;
    private javax.swing.JButton report;
    private javax.swing.JSpinner server_awal;
    private javax.swing.JSpinner server_poli;
    private javax.swing.JSpinner server_poli2;
    private javax.swing.JSpinner server_poli3;
    private javax.swing.JSlider slider;
    private javax.swing.JToggleButton stop;
    // End of variables declaration//GEN-END:variables
}
